### ISSUE TITLE
Initialisation error with .NET Core 3 and SpecFlow 3.1.21-beta

### ISSUE THREAD

**Issue by nsio-stevew** [specsolutions/deveroom-visualstudio#49]
Feels like I'm a little on the bleeding edge here so perhaps my own fault, but hoping the issue can be fairly easily rectified.  The setup is Visual Studio 2019 Preview 1 (installed today), .NET Core 3, Deveroom v1.4.2, xunit v2.4.0.  I was getting some errors with the latest SpecFlow build so I upgraded SpecFlow to v3.1.21-beta.  When I open the feature file and right-click to define steps, I get the following error:

Info: OnActivityStarted: Starting Deveroom...
Info: CreateProjectScope: Initializing project: blahblah.Specs
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v3.0,SpecFlow:3.1.21-beta
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Users\DevAdmin\source\repos\blahblah.Specs\bin\Debug\netcoreapp3.0> C:\Program Files\dotnet\dotnet.exe exec C:\USERS\DEVADMIN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_8FB92FA6\EXTENSIONS\140EZEFW.IX1\Connectors\V2\deveroom-specflow-v2.dll discovery C:\Users\DevAdmin\source\repos\blahblah.Specs\bin\Debug\netcoreapp3.0\blahblah.Specs.dll ""
Exit code: 4
Message: 
Error: Exception has been thrown by the target of an invocation. -> Could not load file or assembly 'TechTalk.SpecFlow, Version=3.1.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) -> Could not load file or assembly 'TechTalk.SpecFlow, Version=3.1.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41'.
Exception: System.Reflection.TargetInvocationException->System.IO.FileLoadException->System.IO.FileLoadException
StackTrace:
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at TechTalk.SpecFlow.Plugins.RuntimePluginLoader.LoadPlugin(String pluginAssemblyName, ITraceListener traceListener)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.LoadPlugin(String pluginPath, IRuntimePluginLoader pluginLoader, RuntimePluginEvents runtimePluginEvents, UnitTestProviderConfiguration unitTestProviderConfigration, ITraceListener traceListener)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.LoadPlugins(IRuntimeConfigurationProvider configurationProvider, ObjectContainer container, RuntimePluginEvents runtimePluginEvents, SpecFlowConfiguration specFlowConfiguration, UnitTestProviderConfiguration unitTestProviderConfigration, Assembly testAssembly)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.CreateGlobalContainer(Assembly testAssembly, IRuntimeConfigurationProvider configurationProvider)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.V30.SpecFlowV30P220Discoverer.GetBindingRegistry(Assembly testAssembly, String configFilePath) in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\V30\SpecFlowV30P220Discoverer.cs:line 17
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(Assembly testAssembly, String testAssemblyPath, String configFilePath) in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector\Discovery\BaseDiscoverer.cs:line 29
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.Discover(Assembly testAssembly, String testAssemblyPath, String configFilePath) in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector\Discovery\BaseDiscoverer.cs:line 21
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Deveroom.VisualStudio.SpecFlowConnector.ReflectionExtensions.ReflectionCallMethod[T](Object obj, String methodName, Type[] parameterTypes, Object[] args) in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector\ReflectionExtensions.cs:line 23
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.ReflectionSpecFlowDiscoverer.Discover(Assembly testAssembly, String testAssemblyPath, String configFilePath) in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\ReflectionSpecFlowDiscoverer.cs:line 20
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process() in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\DiscoveryProcessor.cs:line 32
   at Deveroom.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args) in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector\ConsoleRunner.cs:line 32

Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/specsolutions/deveroom-visualstudio/issues if you cannot fix.
Warning: ShowProblem: User Notification: All steps have been defined in this file already.

I have tried adding the following to the deveroom.json config file but this doesn't seem to help:

{
  "specFlow": {
    "version": "3.1.21-beta"
  }
}

Many thanks in advance.

**Comment by gasparnagy** [comment]
Thx. I haven't tested Deveroom yet with SpecFlow v3.1. I will also try and let you know if I was able to repro your issue.

**Comment by rosslovas** [comment]
Getting the same thing but with .NET Core 2.2.407, VS2019 16.2.5, Deveroom 1.4.2. Same SpecFlow version (3.1.21-beta).

**Comment by gasparnagy** [comment]
This has been fixed and released with v1.4.3.
