### ISSUE TITLE
Step text completion not working

### ISSUE THREAD

**Issue by kryban** [specsolutions/deveroom-visualstudio#66]
Recently installed deveroom, but the step-text-completion is not working for me. 
Ctrl+space is providing me scenario keywords, but there is no further step text-completion.

In the log a see an InvalidOperationException exception as well parserErrors:
 ```
2020-10-29T08:30:33, Verbose, GetSafeMonitoringService: Monitoring service loaded
2020-10-29T08:30:33, Verbose, LoadProjectSystem: Loading VsIdeScope...
2020-10-29T08:30:33, Verbose, .ctor: Creating IDE Scope
2020-10-29T08:30:34, Info, OnActivityStarted: Starting Deveroom...
2020-10-29T08:30:34, Info, CreateProjectScope: Initializing project: TestPr
2020-10-29T08:30:34, Verbose, GetPackageReferences: Exception: System.InvalidOperationException: The operation failed as details for project TestPr could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAndAdditionalMessagesAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.<GetPackageSpecsAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass8_0.<<GetInstalledPackages>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Deveroom.VisualStudio.ProjectSystem.VsProjectScope.GetPackageReferences()
2020-10-29T08:30:34, Info, StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
2020-10-29T08:30:34, Verbose, InitializeBindingRegistry: Initial discovery triggered...
2020-10-29T08:30:34, Verbose, GetSkippedBindingRegistryResult: Uninitialized project settings
2020-10-29T08:30:34, Verbose, InitializeWithDiscoveryService: Creating DeveroomTagger (project: TestPr, SpecFlow: 3.4.31)
2020-10-29T08:30:34, Verbose, SolutionEventListenerOnLoaded: Solution loaded
2020-10-29T08:30:36, Verbose, Parse: Parsed buffer v2 in 226ms on thread 1
2020-10-29T08:30:39, Info, OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v3.1,SpecFlow:3.4.31
2020-10-29T08:30:39, Verbose, ProjectSystemOnProjectsBuilt: Projects built or settings initialized
2020-10-29T08:30:40, Verbose, RunDiscovery: -> Loading plugin D:\temp\deveroomTest\ConsoleApp1\TestPr\bin\Debug\netcoreapp3.1\TechTalk.SpecFlow.NUnit.SpecFlowPlugin.dll
-> Using default config
>>>>>>>>>>
{
  "stepDefinitions": [
    {
      "type": "Given",
      "regex": "^een eerste testgeval$",
      "method": "ConsoleTestsStepDefinitions.GivenEenEersteTestgeval()",
      "sourceLocation": "#0|12|9|14|10"
    },
    {
      "type": "When",
      "regex": "^de trst draait$",
      "method": "ConsoleTestsStepDefinitions.WhenDeTrstDraait()",
      "sourceLocation": "#0|18|9|20|10"
    },
    {
      "type": "Then",
      "regex": "^slaagt de test$",
      "method": "ConsoleTestsStepDefinitions.ThenSlaagtDeTest()",
      "sourceLocation": "#0|24|9|26|10"
    }
  ],
  "sourceFiles": {
    "0": "D:\\temp\\deveroomTest\\ConsoleApp1\\TestPr\\ConsoleTestsStepDefinitions.cs"
  },
  "typeNames": {},
  "specFlowVersion": "D:\\temp\\deveroomTest\\ConsoleApp1\\TestPr\\bin\\Debug\\netcoreapp3.1\\TechTalk.SpecFlow.dll",
  "isFailed": false
}
<<<<<<<<<<

2020-10-29T08:30:40, Info, InvokeDiscovery: 3 step definitions discovered for project TestPr
2020-10-29T08:30:40, Verbose, CalculateSourceLocationTrackingPositions: 3 tracking positions calculated
2020-10-29T08:30:40, Verbose, InvokeDiscoveryWithTimer: Discovery: 764 ms
2020-10-29T08:30:40, Verbose, Parse: Parsed buffer v2 in 13ms on thread 1
2020-10-29T08:30:44, Verbose, RegisterMenuCommands: RegenerateAllFeatureFileCodeBehindCommand registered
2020-10-29T08:31:48, Verbose, Parse: Parsed buffer v3 in 8ms on thread 1
2020-10-29T08:31:49, Verbose, Parse: Parsed buffer v4 in 1ms on thread 1
2020-10-29T08:31:50, Verbose, Parse: Parsed buffer v5 in 2ms on thread 1
2020-10-29T08:31:51, Verbose, ParseAndCollectErrors: ParserErrors: Parser errors:
(15:1): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ExamplesLine, #ScenarioLine, #RuleLine, #Comment, #Empty, got 'Then'
2020-10-29T08:31:51, Verbose, Parse: Parsed buffer v6 in 4ms on thread 1
2020-10-29T08:31:52, Verbose, Parse: Parsed buffer v7 in 6ms on thread 1
2020-10-29T08:31:52, Verbose, Parse: Parsed buffer v8 in 2ms on thread 1
2020-10-29T08:31:53, Verbose, Parse: Parsed buffer v9 in 1ms on thread 1
2020-10-29T08:31:54, Verbose, Parse: Parsed buffer v10 in 4ms on thread 1
2020-10-29T08:31:56, Verbose, Parse: Parsed buffer v23 in 1ms on thread 1
```

Above project is .net core 3.1, just for testing deveroom, having below packages installed: 
SpecFlow  3.4.31
SpecFlow.NUnit  3.4.31
SpecFlow.Tools.MsBuid.Generation  3.4.31

Any ideas about this ?

**Comment by gasparnagy** [comment]
@kryban Did you finally solved this problem?
